

iNext tutorial 
```{r}
library(iNEXT)

data(spider)
str(spider)
spider

inext.test <- iNEXT(spider,
                    q = 0,
                    datatype = "abundance")
inext.test
ggiNEXT(inext.test, 
        color.var = "site",
        facet.var = "none")
ant

data(BCI)
BCI.test.no.zero <- unlist(BCI[1,])

i.zero <- which(BCI.test.no.zero == 0)
BCI.test.no.zero <- BCI.test.no.zero[-i.zero]
```



```{r}
library(FedData)

nlcd <- get_nlcd(study.states, 
                 label = "my.label",
                 year = )
plot(nlcd)
```

```{r}
library(raster)
us <- getData("GADM", country = "USA", level = 1)

study.states <- subset(us,
                       NAME_1 == "Wisconsin" | NAME_1 == "Minnesota" | NAME_1 == "Illinois" | NAME_1 == "Iowa")
plot(study.states)
```


# Plot terricola/impatiens range estimates
```{r}
spatial.bumbles.df %>%
  filter(species == "Bombus terricola" & 
           bin_ag %in% c(1950, 2012)) %>%
  ggplot() + 
  geom_polygon(data = us.county.midwest,
               mapping = aes(x = long,
                             y = lat,
                             group = group),
               fill = "gray60",
               color = "gray50",
               size = 0.25,
               na.rm = TRUE) + 
  geom_jitter(mapping = aes(x = dec_long,
                           y = dec_lat),
             shape = 21,
             size = 3,
             fill = "tomato",
             color = "gray50") +    
  coord_map("stereographic") +
  # facet_wrap(~ species,
  #            labeller = as_labeller(species),
  #            ncol = 5) + 
  facet_wrap(~bin_ag) +
  theme_void()
```

```{r}
plot.species <- c("Bombus impatiens", "Bombus terricola")
  for(i in plot.species) {
    plot <- relabun_bycty.df %>%
      filter(year %in% c(1900, 2012)) %>%
      filter(species == i) %>%
      mutate(bin_ag = year) %>%
      mutate(state_full = abbr2state(state)) %>%
      full_join(ungroup(us.county.midwest),
                by = c("county" = "CNTY_NAME",
                       "state_full" = "region")) %>%
      filter(!is.na(species)) %>%
      ggplot() +
      geom_polygon(mapping = aes(x = long,
                                 y = lat,
                                 group = group,
                                 fill = rel_abun,
                                 color = rel_abun),
                   # color = "gray80",
                   size = 0.25) + 
      # geom_polygon(mapping = aes(x = long,
      #                            y = lat,
      #                            group = group),
      #              color = "black",
      #              fill = NA,
      #              size = 0.25) + 
      # geom_point(inherit.aes = FALSE,
      #            data = spatial.bumbles.df %>%
      #              filter(species == i) %>%
      #              filter(bin_ag %in% c(1900, 2012)) %>%
      #              group_by(bin_ag) %>%
      #              sample_n(size = 50, replace = TRUE),
      #            mapping = aes(x = dec_long,
      #                          y = dec_lat),
      #            shape = 21,
      #            color = "white",
      #            # color = "black",
      #            size = 1) +
      coord_map("stereographic") +
      labs(title = i) +
      scale_fill_viridis_c(option = "inferno",
                           direction = 1,
                           limits = c(0, 1)) +
      scale_color_viridis_c(option = "inferno",
                           direction = 1,
                           limits = c(0, 1)) +
      # scale_fill_gradient(low = "#FFFFFF",
      #                     high = "#59262F") +
      facet_grid(~ bin_ag) + 
      theme_void()
    ggsave(paste("../../p_website/figures/",
                 tolower(gsub(" ", "_", i)),
                 ".eps",
                 sep = ""),
           width = 6)
    print(plot)
  }
```

```{r}
us.county.midwest$unique <- paste(us.county.midwest$CNTY_NAME,
                                  us.county.midwest$region,
                                  sep = ".")
unique(us.county.midwest$unique)
```

```{r}
spatial.bumbles2.df %>%
  filter(og_database == "gbif") %>%
  distinct(year) %>%
  arrange(desc(year))
```


